name: Deploy to VPS

on:
  push:
    branches: [ "prod" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/Portfolio/
            git fetch origin
            git reset --hard origin/prod
            git checkout prod
            git pull origin prod
            php bin/console asset-map:compile
            php bin/console c:c
